package com.test.client.WSClient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "WSImpl", targetNamespace = "http://test.com/")
public interface WSImpl {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "sayHello", targetNamespace = "http://test.com/", className = "com.test.client.WSClient.SayHello")
	@ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://test.com/", className = "com.test.client.WSClient.SayHelloResponse")
	public String sayHello(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "addEmployee", targetNamespace = "http://test.com/", className = "com.test.client.WSClient.AddEmployee")
	@ResponseWrapper(localName = "addEmployeeResponse", targetNamespace = "http://test.com/", className = "com.test.client.WSClient.AddEmployeeResponse")
	public void addEmployee(
			@WebParam(name = "arg0", targetNamespace = "") EmpTO arg0);

	/**
	 * 
	 * @return returns java.util.List<com.test.client.WSClient.EmpTO>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getEmployees", targetNamespace = "http://test.com/", className = "com.test.client.WSClient.GetEmployees")
	@ResponseWrapper(localName = "getEmployeesResponse", targetNamespace = "http://test.com/", className = "com.test.client.WSClient.GetEmployeesResponse")
	public List<EmpTO> getEmployees();

}
