// **********************************************************************
//
// Generated by the ORBacus IDL-to-C++ Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.1

#include <OB/CORBAServer.h>
#include <seq1_WStringValue_skel.h>

#ifndef OB_INTEGER_VERSION
#   error No ORBacus version defined! Is <OB/CORBA.h> included?
#endif

#ifndef OB_NO_VERSION_CHECK
#   if (OB_INTEGER_VERSION != 4010100L)
#       error ORBacus version mismatch!
#   endif
#endif

//
// IDL:org:1.0
//

//
// IDL:org/omg:1.0
//

//
// IDL:org/omg/boxedRMI:1.0
//

//
// IDL:org/omg/boxedRMI/CORBA:1.0
//
