// **********************************************************************
//
// Generated by the ORBacus IDL-to-C++ Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.1

#include <OB/CORBAClient.h>
#include <seq1_WStringValue.h>

#ifndef OB_INTEGER_VERSION
#   error No ORBacus version defined! Is <OB/CORBA.h> included?
#endif

#ifndef OB_NO_VERSION_CHECK
#   if (OB_INTEGER_VERSION != 4010100L)
#       error ORBacus version mismatch!
#   endif
#endif

namespace org
{

namespace omg
{

namespace boxedRMI
{

namespace CORBA
{

::OB::TypeCodeConst _tc_seq1_WStringValue(
"000000000000001e000000bc0086a6b00000003a524d493a5b4c6a6176612e6c616e672e53747"
"2696e673b3a303731444138424537463937313132383a41304630413433383741334242333432"
"00e3f000000012736571315f57537472696e6756616c7565002318000000130000005800bed79"
"00000001e00000048000000000000002349444c3a6f6d672e6f72672f434f5242412f57537472"
"696e6756616c75653a312e3000800000000d57537472696e6756616c756500981a480000001b0"
"000000000000000"
);

} // End of namespace CORBA

} // End of namespace boxedRMI

} // End of namespace omg

} // End of namespace org

//
// RMI:[Ljava.lang.String;:071DA8BE7F971128:A0F0A4387A3BB342
//
const char* org::omg::boxedRMI::CORBA::seq1_WStringValue::_ob_id_ = "RMI:[Ljava.lang.String;:071DA8BE7F971128:A0F0A4387A3BB342";

void
OBDuplicate(org::omg::boxedRMI::CORBA::seq1_WStringValue* p)
{
    CORBA::add_ref(p);
}

void
OBRelease(org::omg::boxedRMI::CORBA::seq1_WStringValue* p)
{
    CORBA::remove_ref(p);
}

CORBA::ValueBase*
org::omg::boxedRMI::CORBA::seq1_WStringValue::_copy_value()
{
    return new seq1_WStringValue(_boxed_in());
}

org::omg::boxedRMI::CORBA::seq1_WStringValue*
org::omg::boxedRMI::CORBA::seq1_WStringValue::_downcast(::CORBA::ValueBase* p)
{
    return dynamic_cast<seq1_WStringValue*>(p);
}

const char*
org::omg::boxedRMI::CORBA::seq1_WStringValue::_OB_typeId() const
{
    return _ob_id_;
}

const char*
org::omg::boxedRMI::CORBA::seq1_WStringValue::_OB_id()
{
    return _ob_id_;
}

void
org::omg::boxedRMI::CORBA::seq1_WStringValue::_OB_marshal(OB::OutputStreamImpl* _ob_out)
{
    ::CORBA::ULong _ob_len0 = _ob_v_.in().length();
    _ob_out -> write_ulong(_ob_len0);
    ::CORBA::WStringValue* const * _ob_buf0 = _ob_v_.in().get_buffer();
    for(::CORBA::ULong _ob_i0 = 0 ; _ob_i0 < _ob_len0 ; _ob_i0++)
    {
        OBMarshal(_ob_buf0[_ob_i0], _ob_out);
    }
}

void
org::omg::boxedRMI::CORBA::seq1_WStringValue::_OB_unmarshal(OB::InputStreamImpl* _ob_in)
{
    ::CORBA::ULong _ob_len0 = _ob_in -> read_ulong();
    _ob_v_.inout().length(_ob_len0);
    ::CORBA::WStringValue* * _ob_buf0 = _ob_v_.inout().get_buffer();
    for(::CORBA::ULong _ob_i0 = 0 ; _ob_i0 < _ob_len0 ; _ob_i0++)
    {
        ::CORBA::remove_ref(_ob_buf0[_ob_i0]);
        OBUnmarshal(_ob_buf0[_ob_i0], _ob_in);
    }
}

void
OBMarshal(org::omg::boxedRMI::CORBA::seq1_WStringValue* v, OB::OutputStreamImpl* out)
{
    out -> write_value(v, org::omg::boxedRMI::CORBA::seq1_WStringValue::_OB_id());
}

void
OBUnmarshal(org::omg::boxedRMI::CORBA::seq1_WStringValue*& v, OB::InputStreamImpl* in)
{
    CORBA::ValueBase* vb = in -> read_value(org::omg::boxedRMI::CORBA::seq1_WStringValue::_OB_id());
    v = org::omg::boxedRMI::CORBA::seq1_WStringValue::_downcast(vb);
}

void
operator<<=(CORBA::Any& any, org::omg::boxedRMI::CORBA::seq1_WStringValue** v)
{
    static OB::ValueBaseInfo info;
    any.replace(org::omg::boxedRMI::CORBA::_tc_seq1_WStringValue, (CORBA::ValueBase*)*v, true, &info);
}

void
operator<<=(CORBA::Any& any, org::omg::boxedRMI::CORBA::seq1_WStringValue* v)
{
    CORBA::add_ref(v);
    any <<= &v;
}

CORBA::Boolean
operator>>=(const CORBA::Any& any, org::omg::boxedRMI::CORBA::seq1_WStringValue*& v)
{
    if(any.check_type(org::omg::boxedRMI::CORBA::_tc_seq1_WStringValue))
    {
        CORBA::ValueBase_var vb;
        if(any >>= CORBA::Any::to_value(vb.out()))
        {
            org::omg::boxedRMI::CORBA::seq1_WStringValue* val = 0;

            if(vb.in() != 0)
            {
                val = org::omg::boxedRMI::CORBA::seq1_WStringValue::_downcast(vb);
                if(val == 0)
                    return false;
                if(!any.info())
                    (CORBA::Any&)any <<= val;
            }

            v = val;
            return true;
        }
    }

    return false;
}

CORBA::ValueBase*
org::omg::boxedRMI::CORBA::seq1_WStringValue_init::create_for_unmarshal()
{
    return new ::org::omg::boxedRMI::CORBA::seq1_WStringValue;
}

org::omg::boxedRMI::CORBA::seq1_WStringValue_init*
org::omg::boxedRMI::CORBA::seq1_WStringValue_init::_downcast(::CORBA::ValueFactory f)
{
    return dynamic_cast<seq1_WStringValue_init*>(f);
}
