// **********************************************************************
//
// Generated by the ORBacus IDL-to-C++ Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.1

#include <OB/CORBAClient.h>
#include <seq1_StackTraceElement.h>

#ifndef OB_INTEGER_VERSION
#   error No ORBacus version defined! Is <OB/CORBA.h> included?
#endif

#ifndef OB_NO_VERSION_CHECK
#   if (OB_INTEGER_VERSION != 4010100L)
#       error ORBacus version mismatch!
#   endif
#endif

namespace java
{

namespace lang
{

} // End of namespace lang

} // End of namespace java

namespace org
{

namespace omg
{

namespace boxedRMI
{

namespace java
{

namespace lang
{

::OB::TypeCodeConst _tc_seq1_StackTraceElement(
"000000000000001e000001580001000000000045524d493a5b4c6a6176612e6c616e672e53746"
"1636b5472616365456c656d656e743b3a434433384639393330454138414145433a3631303943"
"353941323633364444383500bed5f800000017736571315f537461636b5472616365456c656d6"
"56e7400f000000013000000e4000000010000001d000000d20000000000000042524d493a6a61"
"76612e6c616e672e537461636b5472616365456c656d656e743a4344333846393933304541384"
"14145433a3631303943353941323633364444383500000000000012537461636b547261636545"
"6c656d656e7400000000000000000000010000000f6465636c6172696e67436c6173730017000"
"0001e00000048000000010000002349444c3a6f6d672e6f72672f434f5242412f57537472696e"
"6756616c75653a312e3000010000000d57537472696e6756616c7565008772980000001b00000"
"0000000000000000000"
);

} // End of namespace lang

} // End of namespace java

} // End of namespace boxedRMI

} // End of namespace omg

} // End of namespace org

//
// RMI:[Ljava.lang.StackTraceElement;:CD38F9930EA8AAEC:6109C59A2636DD85
//
const char* org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_ob_id_ = "RMI:[Ljava.lang.StackTraceElement;:CD38F9930EA8AAEC:6109C59A2636DD85";

void
OBDuplicate(org::omg::boxedRMI::java::lang::seq1_StackTraceElement* p)
{
    CORBA::add_ref(p);
}

void
OBRelease(org::omg::boxedRMI::java::lang::seq1_StackTraceElement* p)
{
    CORBA::remove_ref(p);
}

CORBA::ValueBase*
org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_copy_value()
{
    return new seq1_StackTraceElement(_boxed_in());
}

org::omg::boxedRMI::java::lang::seq1_StackTraceElement*
org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_downcast(CORBA::ValueBase* p)
{
    return dynamic_cast<seq1_StackTraceElement*>(p);
}

const char*
org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_OB_typeId() const
{
    return _ob_id_;
}

const char*
org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_OB_id()
{
    return _ob_id_;
}

void
org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_OB_marshal(OB::OutputStreamImpl* _ob_out)
{
    CORBA::ULong _ob_len0 = _ob_v_.in().length();
    _ob_out -> write_ulong(_ob_len0);
    ::java::lang::StackTraceElement* const * _ob_buf0 = _ob_v_.in().get_buffer();
    for(CORBA::ULong _ob_i0 = 0 ; _ob_i0 < _ob_len0 ; _ob_i0++)
    {
        OBMarshal(_ob_buf0[_ob_i0], _ob_out);
    }
}

void
org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_OB_unmarshal(OB::InputStreamImpl* _ob_in)
{
    CORBA::ULong _ob_len0 = _ob_in -> read_ulong();
    _ob_v_.inout().length(_ob_len0);
    ::java::lang::StackTraceElement* * _ob_buf0 = _ob_v_.inout().get_buffer();
    for(CORBA::ULong _ob_i0 = 0 ; _ob_i0 < _ob_len0 ; _ob_i0++)
    {
        CORBA::remove_ref(_ob_buf0[_ob_i0]);
        OBUnmarshal(_ob_buf0[_ob_i0], _ob_in);
    }
}

void
OBMarshal(org::omg::boxedRMI::java::lang::seq1_StackTraceElement* v, OB::OutputStreamImpl* out)
{
    out -> write_value(v, org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_OB_id());
}

void
OBUnmarshal(org::omg::boxedRMI::java::lang::seq1_StackTraceElement*& v, OB::InputStreamImpl* in)
{
    CORBA::ValueBase* vb = in -> read_value(org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_OB_id());
    v = org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_downcast(vb);
}

void
operator<<=(CORBA::Any& any, org::omg::boxedRMI::java::lang::seq1_StackTraceElement** v)
{
    static OB::ValueBaseInfo info;
    any.replace(org::omg::boxedRMI::java::lang::_tc_seq1_StackTraceElement, (CORBA::ValueBase*)*v, true, &info);
}

void
operator<<=(CORBA::Any& any, org::omg::boxedRMI::java::lang::seq1_StackTraceElement* v)
{
    CORBA::add_ref(v);
    any <<= &v;
}

CORBA::Boolean
operator>>=(const CORBA::Any& any, org::omg::boxedRMI::java::lang::seq1_StackTraceElement*& v)
{
    if(any.check_type(org::omg::boxedRMI::java::lang::_tc_seq1_StackTraceElement))
    {
        CORBA::ValueBase_var vb;
        if(any >>= CORBA::Any::to_value(vb.out()))
        {
            org::omg::boxedRMI::java::lang::seq1_StackTraceElement* val = 0;

            if(vb.in() != 0)
            {
                val = org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_downcast(vb);
                if(val == 0)
                    return false;
                if(!any.info())
                    (CORBA::Any&)any <<= val;
            }

            v = val;
            return true;
        }
    }

    return false;
}

CORBA::ValueBase*
org::omg::boxedRMI::java::lang::seq1_StackTraceElement_init::create_for_unmarshal()
{
    return new ::org::omg::boxedRMI::java::lang::seq1_StackTraceElement;
}

org::omg::boxedRMI::java::lang::seq1_StackTraceElement_init*
org::omg::boxedRMI::java::lang::seq1_StackTraceElement_init::_downcast(CORBA::ValueFactory f)
{
    return dynamic_cast<seq1_StackTraceElement_init*>(f);
}
