// **********************************************************************
//
// Generated by the ORBacus IDL-to-C++ Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.1

#ifndef ___seq1_StackTraceElement_skel_h__
#define ___seq1_StackTraceElement_skel_h__

#include <seq1_StackTraceElement.h>

#include <java/lang/StackTraceElement_skel.h>

#ifndef OB_INTEGER_VERSION
#   error No ORBacus version defined! Is <OB/CORBA.h> included?
#endif

#ifndef OB_NO_VERSION_CHECK
#   if (OB_INTEGER_VERSION != 4010100L)
#       error ORBacus version mismatch!
#   endif
#endif

//
// IDL:java:1.0
//
namespace POA_java
{

//
// IDL:java/lang:1.0
//
namespace lang
{

} // End of namespace lang

} // End of namespace POA_java

//
// IDL:org:1.0
//
namespace POA_org
{

//
// IDL:org/omg:1.0
//
namespace omg
{

//
// IDL:org/omg/boxedRMI:1.0
//
namespace boxedRMI
{

//
// IDL:org/omg/boxedRMI/java:1.0
//
namespace java
{

//
// IDL:org/omg/boxedRMI/java/lang:1.0
//
namespace lang
{

} // End of namespace lang

} // End of namespace java

} // End of namespace boxedRMI

} // End of namespace omg

} // End of namespace POA_org

//
// IDL:java:1.0
//
namespace OBDirectStubImpl_java
{

//
// IDL:java/lang:1.0
//
namespace lang
{

} // End of namespace lang

} // End of namespace OBDirectStubImpl_java

//
// IDL:org:1.0
//
namespace OBDirectStubImpl_org
{

//
// IDL:org/omg:1.0
//
namespace omg
{

//
// IDL:org/omg/boxedRMI:1.0
//
namespace boxedRMI
{

//
// IDL:org/omg/boxedRMI/java:1.0
//
namespace java
{

//
// IDL:org/omg/boxedRMI/java/lang:1.0
//
namespace lang
{

} // End of namespace lang

} // End of namespace java

} // End of namespace boxedRMI

} // End of namespace omg

} // End of namespace OBDirectStubImpl_org

#endif
