<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso8859-1">
<meta description="iPlanet Application Server Caching Sample Application 
   Results">
<!-- disable browser caching so that it doesn't mask server caching. -->
<meta http-equiv="pragma" content="no-cache">
<meta http-equiv="expires" content="-1">
<title>Servlet Caching Sample</title>
</head>
<body bgcolor="#FFFFFF">
<h2>Servlet Cache Sample</h2>
The following was generated by : 
<blockquote><strong>a JSP template</strong></blockquote>

The date this content was created was : 
<blockquote><strong>
<%= new java.util.Date().toString() %>
</strong></blockquote>

The input string passed into this servlet was:
<blockquote><strong>
<%= request.getParameter("inputtext") %>
</strong></blockquote>

<a href="index.html">Return to Start Page</a>
</body></html>
