package com.test.client.HelloClient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * HelloService service = new HelloService();
 * HelloWSImpl portType = service.getHelloServicePort();
 * portType.sayHello(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "HelloService", targetNamespace = "http://test.com/", wsdlLocation = "http://localhost:8080/MyWS/HelloServicePort?wsdl")
public class HelloService extends Service {

	private final static URL HELLOSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.test.client.HelloClient.HelloService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.test.client.HelloClient.HelloService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/MyWS/HelloServicePort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/MyWS/HelloServicePort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		HELLOSERVICE_WSDL_LOCATION = url;
	}

	public HelloService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public HelloService() {
		super(HELLOSERVICE_WSDL_LOCATION, new QName("http://test.com/",
				"HelloService"));
	}

	/**
	 * 
	 * @return returns HelloWSImpl
	 */
	@WebEndpoint(name = "HelloServicePort")
	public HelloWSImpl getHelloServicePort() {
		return super.getPort(new QName("http://test.com/", "HelloServicePort"),
				HelloWSImpl.class);
	}

}
