package com.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-23T02:01:38.298+05:30
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://test.com/", name = "WS")
@XmlSeeAlso({ObjectFactory.class})
public interface WS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://test.com/", className = "com.test.SayHello")
    @WebMethod(action = "urn:SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://test.com/", className = "com.test.SayHelloResponse")
    public java.lang.String sayHello(@WebParam(name = "arg0", targetNamespace = "")  java.lang.String arg0  );
}
