<!--
 Copyright 2002 Sun Microsystems, Inc. All rights reserved.
 
 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions
 are met:
 
 - Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
 
 - Redistribution in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in
   the documentation and/or other materials provided with the
   distribution.
 
 Neither the name of Sun Microsystems, Inc. or the names of
 contributors may be used to endorse or promote products derived
 from this software without specific prior written permission.
 
 This software is provided "AS IS," without a warranty of any
 kind. ALL EXPRESS OR IMPLIED CONDITIONS, REPRESENTATIONS AND
 WARRANTIES, INCLUDING ANY IMPLIED WARRANTY OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT, ARE HEREBY
 EXCLUDED. SUN AND ITS LICENSORS SHALL NOT BE LIABLE FOR ANY DAMAGES
 SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR
 DISTRIBUTING THE SOFTWARE OR ITS DERIVATIVES. IN NO EVENT WILL SUN
 OR ITS LICENSORS BE LIABLE FOR ANY LOST REVENUE, PROFIT OR DATA, OR
 FOR DIRECT, INDIRECT, SPECIAL, CONSEQUENTIAL, INCIDENTAL OR
 PUNITIVE DAMAGES, HOWEVER CAUSED AND REGARDLESS OF THE THEORY OF
 LIABILITY, ARISING OUT OF THE USE OF OR INABILITY TO USE SOFTWARE,
 EVEN IF SUN HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
 
 You acknowledge that Software is not designed, licensed or intended
 for use in the design, construction, operation or maintenance of
 any nuclear facility.
-->

<%--
 % $Id: index.jsp,v 1.1.2.2 2002/05/16 21:10:49 subbara Exp $
 % Copyright 2001 Sun Microsystems, Inc. All rights reserved.
 % Copyright 2001 Sun Microsystems, Inc. Tous droits r√àserv√às.
--%>

<html>
<head>
<title>Java[tm] Pet Store Demo 1.3 on SunONE App Server</title>
</head>
<body>

<table width="100%" cellpadding="5" cellspacing="0" border="0">
<tr>
<td bgcolor="#000033">
<font color="#FFFFFF"><b>Java[tm] Pet Store Demo 1.3</b></font>
</td>
<td bgcolor="#000033">
<div align="right"><a
href="http://java.sun.com/j2ee/blueprints/"><font
color="#CCCCFF"><b>J2EE[tm] BluePrints</b></font></a></div>
</td>
</tr>
</table>

<h1><FONT COLOR="RED">Welcome to Java&#153; Pet Store Demo 1.3 Running on SunONE Application Server!</FONT></h1>

<p>The Java&#153; Pet Store Demo is a sample application brought to
you by the <a href="http://java.sun.com/j2ee/blueprints/">Java 2
Platform, Enterprise Edition BluePrints (J2EE&#153; BluePrints)</a>
program at <a href="http://java.sun.com">Java Software</a>, <a
href="http://sun.com">Sun Microsystems</a>.</p>

<p>This sample application demonstrates how to use the capabilities of
the J2EE platform to develop flexible, scalable, cross-platform
e-business applications. It comes with full source code and
documentation, so you can experiment with J2EE technology and learn
how to use it to build your own enterprise solutions.</p>

<!--
<p>To start using the demo, <a href="/petstore/main.screen">enter the
store</a>. </p>

<p>You may also forcefully <a href="Populate?success_page=//rcvr/Populate%3fsuccess_page%3d//petstore"><b>repopulate
the demo's database</b></a>. (Be prepared to wait for a while as the
database is populated.)</p>
-->

<p>To start using the demo, <a href=/petstore/main.screen>Enter the Store</a>. </p>

<p>To manage suppliers and inventory ,<a href=/rcvr>Enter the Supplier</a>. </p>

<p>To use the Admin Clinet based on JavaWebStart, <a href="/admin/">Enter Administrator Client</a>.</p>

<h2><FONT COLOR="RED">About SunONE Application Server</FONT></h2>

<p>The SunONE Application Server provides a robust J2EE1.3 platform for the development, deployment, and management of application services 
to a broad range of servers, clients, and devices. The SunONE Application Server maximizes application reuse and developer collaboration 
and demonstrates the potential of leveraging Java technology for large-scale Web and wireless applications.

The SunONE App Server is the foundation for the Sun Open Network Environment
<p>Check out this URL for more information about Sun ONE software <code><a
href="http://www.sun.com/software/">http://wwww.sun.com/software/</a></code>.</p>
</p>

<h2>About J2EE BluePrints</h2>

<p>The J2EE BluePrints program defines the application programming
model for the J2EE platform. It provides best practice guidelines and
architectural recommendations for real-world application scenarios to
enable developers to build portable, scalable, and robust applications
using J2EE technology.</p>

<p>The J2EE BluePrints program and the Java Pet Store Demo are
showcased in the upcoming second edition of <i>Designing Enterprise
Applications with the Java 2 Platform, Enterprise Edition</i>. The
first edition of this best-selling book, is available at bookstores
everywhere, including <a
href="http://www.digitalguru.com/product_detail.asp?catalog%5Fname=Books&product%5Fid=0201702770">DigitalGuru</a>
and <a
href="http://www.amazon.com/exec/obidos/ISBN=0201702770/javasoftsunmicroA/">Amazon.com</a>.</p>

<p>Check out the J2EE BluePrints Web site at <code><a
href="http://java.sun.com/j2ee/blueprints/">http://java.sun.com/j2ee/blueprints/</a></code>.</p>

<p><hr noshade="noshade" />Copyright &copy; 2001 Sun Microsystems,
Inc. All Rights Reserved.</p>

</body>
</html>


