
package test.ws.client;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.spi.Provider;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.4
 * Generated source version: 2.1
 *
 */
@WebServiceClient(name = "GetPriceSvc_WS_Name", targetNamespace = "http://ws.svc.getprc.jsca.enterprisetest.oracle.com", wsdlLocation = "http://churchill:7001/JSca_GetTotPrice_CTX/GetPriceSvc_WS_URI?wsdl")
public class GetPriceSvcWS
    extends Service
{

    private final static URL GETPRICESVCWS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(test.ws.client.GetPriceSvcWS.class.getName());

    static {
        URL url = null;
        try {
            Provider provider = Provider.provider();
            Class wlsProviderClass = null;
            Method wlsLocateWsdl = null;
            try {
                wlsProviderClass = Class.forName("weblogic.wsee.jaxws.spi.WLSProvider");
                wlsLocateWsdl = wlsProviderClass.getMethod("locateWsdl", Class.class);
            } catch (ClassNotFoundException cnfe) {
            } catch (NoSuchMethodException nsme) {
            }
            if ((wlsLocateWsdl!= null)&&wlsProviderClass.isAssignableFrom(provider.getClass())) {
                try {
                    url = ((URL) wlsLocateWsdl.invoke(provider, test.ws.client.GetPriceSvcWS.class));
                } catch (IllegalAccessException iae) {
                } catch (IllegalArgumentException ia) {
                } catch (InvocationTargetException ite) {
                }
            }
            if (url == null) {
                URL baseUrl;
                baseUrl = test.ws.client.GetPriceSvcWS.class.getResource(".");
                url = new URL(baseUrl, "GetPriceSvc_WS_URI.xml");
            }
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'GetPriceSvc_WS_URI.xml', retrying as a local file");
            logger.warning(e.getMessage());
        }
        GETPRICESVCWS_WSDL_LOCATION = url;
    }

    public GetPriceSvcWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetPriceSvcWS() {
        super(GETPRICESVCWS_WSDL_LOCATION, new QName("http://ws.svc.getprc.jsca.enterprisetest.oracle.com", "GetPriceSvc_WS_Name"));
    }

    /**
     *
     * @return
     *     returns IGetPrice
     */
    @WebEndpoint(name = "GetPriceSvc_WS_Port")
    public IGetPrice getGetPriceSvcWSPort() {
        return super.getPort(new QName("http://ws.svc.getprc.jsca.enterprisetest.oracle.com", "GetPriceSvc_WS_Port"), IGetPrice.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGetPrice
     */
    @WebEndpoint(name = "GetPriceSvc_WS_Port")
    public IGetPrice getGetPriceSvcWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.svc.getprc.jsca.enterprisetest.oracle.com", "GetPriceSvc_WS_Port"), IGetPrice.class, features);
    }

}
