
package test.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.4
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IGetPrice", targetNamespace = "http://ws.svc.getprc.jsca.enterprisetest.oracle.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IGetPrice {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTotalPrice", targetNamespace = "http://ws.svc.getprc.jsca.enterprisetest.oracle.com", className = "test.ws.client.GetTotalPrice")
    @ResponseWrapper(localName = "getTotalPriceResponse", targetNamespace = "http://ws.svc.getprc.jsca.enterprisetest.oracle.com", className = "test.ws.client.GetTotalPriceResponse")
    public double getTotalPrice(
        @WebParam(name = "arg0", targetNamespace = "")
        ShoppingCart arg0);

}
