// **********************************************************************
//
// Generated by the ORBacus IDL-to-C++ Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.1

#include <OB/CORBAClient.h>
#include <ClassDesc.h>

#ifndef OB_INTEGER_VERSION
#   error No ORBacus version defined! Is <OB/CORBA.h> included?
#endif

#ifndef OB_NO_VERSION_CHECK
#   if (OB_INTEGER_VERSION != 4010100L)
#       error ORBacus version mismatch!
#   endif
#endif

namespace javax
{

namespace rmi
{

namespace CORBA
{

::OB::TypeCodeConst _tc_ClassDesc(
"000000000000001d000001220090c3a000000040524d493a6a617661782e726d692e434f52424"
"12e436c617373446573633a324241424441303435383741444343433a43464246303243463532"
"393431373642000000000a436c61737344657363000000000000000000000200000009636f646"
"562617365009824c00000001e00000048009874d00000002349444c3a6f6d672e6f72672f434f"
"5242412f57537472696e6756616c75653a312e3000030000000d57537472696e6756616c75650"
"0882a800000001b0000000000009d980000000672657069640000020000001e00000048000000"
"020000002349444c3a6f6d672e6f72672f434f5242412f57537472696e6756616c75653a312e3"
"000000000000d57537472696e6756616c75650084aa480000001b000000000000"
);

} // End of namespace CORBA

} // End of namespace rmi

} // End of namespace javax

//
// RMI:javax.rmi.CORBA.ClassDesc:2BABDA04587ADCCC:CFBF02CF5294176B
//
const char* javax::rmi::CORBA::ClassDesc::_ob_id_ = "RMI:javax.rmi.CORBA.ClassDesc:2BABDA04587ADCCC:CFBF02CF5294176B";

void
OBDuplicate(javax::rmi::CORBA::ClassDesc* p)
{
    ::CORBA::add_ref(p);
}

void
OBRelease(javax::rmi::CORBA::ClassDesc* p)
{
    ::CORBA::remove_ref(p);
}

javax::rmi::CORBA::ClassDesc*
javax::rmi::CORBA::ClassDesc::_downcast(::CORBA::ValueBase* p)
{
    return dynamic_cast<ClassDesc*>(p);
}

javax::rmi::CORBA::ClassDesc*
javax::rmi::CORBA::ClassDesc::_downcast(::CORBA::AbstractBase_ptr p)
{
    if(!::CORBA::is_nil(p))
    {
        ::CORBA::ValueBase_var v = p -> _to_value();
        return _downcast(v);
    }
    return 0;
}

const char*
javax::rmi::CORBA::ClassDesc::_OB_typeId() const
{
    return _ob_id_;
}

const char*
javax::rmi::CORBA::ClassDesc::_OB_id()
{
    return _ob_id_;
}

void
javax::rmi::CORBA::ClassDesc::_OB_marshal(OB::OutputStreamImpl* _ob_out)
{
    OBMarshal(codebase(), _ob_out);
    OBMarshal(repid(), _ob_out);
}

void
javax::rmi::CORBA::ClassDesc::_OB_unmarshal(OB::InputStreamImpl* _ob_in)
{
    ::CORBA::WStringValue_var _ob_m0;
    OBUnmarshal(_ob_m0.out(), _ob_in);
    codebase(_ob_m0);
    ::CORBA::WStringValue_var _ob_m1;
    OBUnmarshal(_ob_m1.out(), _ob_in);
    repid(_ob_m1);
}

void
OBMarshal(javax::rmi::CORBA::ClassDesc* v, OB::OutputStreamImpl* out)
{
    out -> write_value(v, javax::rmi::CORBA::ClassDesc::_OB_id());
}

void
OBUnmarshal(javax::rmi::CORBA::ClassDesc*& v, OB::InputStreamImpl* in)
{
    CORBA::ValueBase* vb = in -> read_value(javax::rmi::CORBA::ClassDesc::_OB_id());
    v = javax::rmi::CORBA::ClassDesc::_downcast(vb);
}

void
operator<<=(CORBA::Any& any, javax::rmi::CORBA::ClassDesc** v)
{
    static OB::ValueBaseInfo info;
    any.replace(javax::rmi::CORBA::_tc_ClassDesc, (CORBA::ValueBase*)*v, true, &info);
}

void
operator<<=(CORBA::Any& any, javax::rmi::CORBA::ClassDesc* v)
{
    ::CORBA::add_ref(v);
    any <<= &v;
}

CORBA::Boolean
operator>>=(const CORBA::Any& any, javax::rmi::CORBA::ClassDesc*& v)
{
    if(any.check_type(javax::rmi::CORBA::_tc_ClassDesc))
    {
        CORBA::ValueBase_var vb;
        if(any >>= CORBA::Any::to_value(vb.out()))
        {
            javax::rmi::CORBA::ClassDesc* val = 0;

            if(vb.in() != 0)
            {
                val = javax::rmi::CORBA::ClassDesc::_downcast(vb);
                if(val == 0)
                    return false;
                if(!any.info())
                    (CORBA::Any&)any <<= val;
            }

            v = val;
            return true;
        }
    }

    return false;
}

::CORBA::ValueBase*
javax::rmi::CORBA::ClassDesc_init::create_for_unmarshal()
{
    return new ::OBV_javax::rmi::CORBA::ClassDesc;
}

javax::rmi::CORBA::ClassDesc_init*
javax::rmi::CORBA::ClassDesc_init::_downcast(::CORBA::ValueFactory f)
{
    return dynamic_cast<ClassDesc_init*>(f);
}

//
// RMI:javax.rmi.CORBA.ClassDesc:2BABDA04587ADCCC:CFBF02CF5294176B
//
OBV_javax::rmi::CORBA::ClassDesc::ClassDesc()
{
}

OBV_javax::rmi::CORBA::ClassDesc::ClassDesc(::CORBA::WStringValue* _ob_codebase,
                                            ::CORBA::WStringValue* _ob_repid)
    : _obv_codebase_(_ob_codebase),
      _obv_repid_(_ob_repid)
{
    ::CORBA::add_ref(_obv_codebase_);
    ::CORBA::add_ref(_obv_repid_);
}

OBV_javax::rmi::CORBA::ClassDesc::~ClassDesc()
{
}

CORBA::ValueBase*
OBV_javax::rmi::CORBA::ClassDesc::_copy_value()
{
    return new ClassDesc(codebase(), repid());
}

//
// IDL:javax/rmi/CORBA/ClassDesc/codebase:1.0
//
void
OBV_javax::rmi::CORBA::ClassDesc::codebase(::CORBA::WStringValue* _ob_a)
{
    _obv_codebase_ = _ob_a;
    ::CORBA::add_ref(_obv_codebase_);
}

::CORBA::WStringValue*
OBV_javax::rmi::CORBA::ClassDesc::codebase() const
{
    return _obv_codebase_.in();
}

//
// IDL:javax/rmi/CORBA/ClassDesc/repid:1.0
//
void
OBV_javax::rmi::CORBA::ClassDesc::repid(::CORBA::WStringValue* _ob_a)
{
    _obv_repid_ = _ob_a;
    ::CORBA::add_ref(_obv_repid_);
}

::CORBA::WStringValue*
OBV_javax::rmi::CORBA::ClassDesc::repid() const
{
    return _obv_repid_.in();
}
