// **********************************************************************
//
// Generated by the ORBacus IDL-to-C++ Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.1

#ifndef ___ClassDesc_h__
#define ___ClassDesc_h__

#include <OB/orb.h>

#ifndef OB_INTEGER_VERSION
#   error No ORBacus version defined! Is <OB/CORBA.h> included?
#endif

#ifndef OB_NO_VERSION_CHECK
#   if (OB_INTEGER_VERSION != 4010100L)
#       error ORBacus version mismatch!
#   endif
#endif

namespace javax
{

namespace rmi
{

namespace CORBA
{

class ClassDesc;

extern OB::TypeCodeConst _tc_ClassDesc;

} // End of namespace CORBA

} // End of namespace rmi

} // End of namespace javax

void OBDuplicate(javax::rmi::CORBA::ClassDesc*);
void OBRelease(javax::rmi::CORBA::ClassDesc*);

void OBMarshal(javax::rmi::CORBA::ClassDesc*, OB::OutputStreamImpl*);
void OBUnmarshal(javax::rmi::CORBA::ClassDesc*&, OB::InputStreamImpl*);

namespace javax
{

namespace rmi
{

namespace CORBA
{

typedef OB::ObjVar< ClassDesc > ClassDesc_var;
typedef OB::ObjOut< ClassDesc > ClassDesc_out;

} // End of namespace CORBA

} // End of namespace rmi

} // End of namespace javax

namespace OBStubImpl_javax
{

namespace rmi
{

namespace CORBA
{

} // End of namespace CORBA

} // End of namespace rmi

} // End of namespace OBStubImpl_javax

namespace OBStubImpl_javax
{

namespace rmi
{

namespace CORBA
{

} // End of namespace CORBA

} // End of namespace rmi

} // End of namespace OBStubImpl_javax

//
// IDL:javax:1.0
//
namespace javax
{

//
// IDL:javax/rmi:1.0
//
namespace rmi
{

//
// IDL:javax/rmi/CORBA:1.0
//
namespace CORBA
{

//
// RMI:javax.rmi.CORBA.ClassDesc:2BABDA04587ADCCC:CFBF02CF5294176B
//
class ClassDesc : virtual public ::CORBA::ValueBase
{
    void operator=(const ClassDesc&);

    static const char* _ob_id_;

protected:

    ClassDesc() { }
    virtual ~ClassDesc() { }

public:

    typedef ClassDesc_var _var_type;

    static ClassDesc* _downcast(::CORBA::ValueBase*);
    static ClassDesc* _downcast(::CORBA::AbstractBase_ptr);

protected:

    //
    // IDL:javax/rmi/CORBA/ClassDesc/codebase:1.0
    //
    virtual void codebase(::CORBA::WStringValue*) = 0;
    virtual ::CORBA::WStringValue* codebase() const = 0;

    //
    // IDL:javax/rmi/CORBA/ClassDesc/repid:1.0
    //
    virtual void repid(::CORBA::WStringValue*) = 0;
    virtual ::CORBA::WStringValue* repid() const = 0;

public:

    static const char* _OB_id();

    virtual const char* _OB_typeId() const;

    virtual void _OB_marshal(OB::OutputStreamImpl*);
    virtual void _OB_unmarshal(OB::InputStreamImpl*);
};

class ClassDesc_init : public ::CORBA::ValueFactoryBase
{
    virtual ::CORBA::ValueBase* create_for_unmarshal();

public:

    ClassDesc_init()
    {
    }

    virtual ~ClassDesc_init()
    {
    }

    static ClassDesc_init* _downcast(::CORBA::ValueFactory);
};

} // End of namespace CORBA

} // End of namespace rmi

} // End of namespace javax

//
// IDL:javax:1.0
//
namespace OBProxy_javax
{

//
// IDL:javax/rmi:1.0
//
namespace rmi
{

//
// IDL:javax/rmi/CORBA:1.0
//
namespace CORBA
{

} // End of namespace CORBA

} // End of namespace rmi

} // End of namespace OBProxy_javax

//
// IDL:javax:1.0
//
namespace OBStubImpl_javax
{

//
// IDL:javax/rmi:1.0
//
namespace rmi
{

//
// IDL:javax/rmi/CORBA:1.0
//
namespace CORBA
{

} // End of namespace CORBA

} // End of namespace rmi

} // End of namespace OBStubImpl_javax

//
// IDL:javax:1.0
//
namespace OBMarshalStubImpl_javax
{

//
// IDL:javax/rmi:1.0
//
namespace rmi
{

//
// IDL:javax/rmi/CORBA:1.0
//
namespace CORBA
{

} // End of namespace CORBA

} // End of namespace rmi

} // End of namespace OBMarshalStubImpl_javax

//
// IDL:javax:1.0
//
namespace OBV_javax
{

//
// IDL:javax/rmi:1.0
//
namespace rmi
{

//
// IDL:javax/rmi/CORBA:1.0
//
namespace CORBA
{

//
// RMI:javax.rmi.CORBA.ClassDesc:2BABDA04587ADCCC:CFBF02CF5294176B
//
class ClassDesc : virtual public ::javax::rmi::CORBA::ClassDesc,
                  virtual public ::CORBA::DefaultValueRefCountBase
{
    void operator=(const ClassDesc&);

    ::CORBA::WStringValue_var _obv_codebase_;
    ::CORBA::WStringValue_var _obv_repid_;

public:

    ClassDesc();
    ClassDesc(::CORBA::WStringValue*,
              ::CORBA::WStringValue*);
    virtual ~ClassDesc();

    virtual ::CORBA::ValueBase* _copy_value();

protected:

    //
    // IDL:javax/rmi/CORBA/ClassDesc/codebase:1.0
    //
    virtual void codebase(::CORBA::WStringValue*);
    virtual ::CORBA::WStringValue* codebase() const;

    //
    // IDL:javax/rmi/CORBA/ClassDesc/repid:1.0
    //
    virtual void repid(::CORBA::WStringValue*);
    virtual ::CORBA::WStringValue* repid() const;
};

} // End of namespace CORBA

} // End of namespace rmi

} // End of namespace OBV_javax

//
// RMI:javax.rmi.CORBA.ClassDesc:2BABDA04587ADCCC:CFBF02CF5294176B
//
void operator<<=(CORBA::Any&, javax::rmi::CORBA::ClassDesc**);
void operator<<=(CORBA::Any&, javax::rmi::CORBA::ClassDesc*);
CORBA::Boolean operator>>=(const CORBA::Any&, javax::rmi::CORBA::ClassDesc*&);

inline void
operator<<=(CORBA::Any_var& any, javax::rmi::CORBA::ClassDesc** val)
{
    any.inout() <<= val;
}

inline void
operator<<=(CORBA::Any_var& any, javax::rmi::CORBA::ClassDesc* val)
{
    any.inout() <<= val;
}

inline CORBA::Boolean
operator>>=(const CORBA::Any_var& any, javax::rmi::CORBA::ClassDesc*& val)
{
    return any.in() >>= val;
}

#endif
