// **********************************************************************
//
// Generated by the ORBacus IDL-to-C++ Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.1

#ifndef ___ClassDesc_skel_h__
#define ___ClassDesc_skel_h__

#include <ClassDesc.h>

#include <OB/orb_skel.h>

#ifndef OB_INTEGER_VERSION
#   error No ORBacus version defined! Is <OB/CORBA.h> included?
#endif

#ifndef OB_NO_VERSION_CHECK
#   if (OB_INTEGER_VERSION != 4010100L)
#       error ORBacus version mismatch!
#   endif
#endif

//
// IDL:javax:1.0
//
namespace POA_javax
{

//
// IDL:javax/rmi:1.0
//
namespace rmi
{

//
// IDL:javax/rmi/CORBA:1.0
//
namespace CORBA
{

} // End of namespace CORBA

} // End of namespace rmi

} // End of namespace POA_javax

//
// IDL:javax:1.0
//
namespace OBDirectStubImpl_javax
{

//
// IDL:javax/rmi:1.0
//
namespace rmi
{

//
// IDL:javax/rmi/CORBA:1.0
//
namespace CORBA
{

} // End of namespace CORBA

} // End of namespace rmi

} // End of namespace OBDirectStubImpl_javax

#endif
