package com.test;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * EmpWS service = new EmpWS();
 * WSImpl portType = service.getEmpServices();
 * portType.sayHello(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "EmpWS", targetNamespace = "http://test.com/", wsdlLocation = "file:/D:/WORKSPACE/WS/WebRoot/WEB-INF/wsdl/EmpWS.wsdl")
public class EmpWS extends Service {

	private final static URL EMPWS_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.test.EmpWS.class
			.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.test.EmpWS.class.getResource(".");
			url = new URL(baseUrl,
					"file:/D:/WORKSPACE/WS/WebRoot/WEB-INF/wsdl/EmpWS.wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/WORKSPACE/WS/WebRoot/WEB-INF/wsdl/EmpWS.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		EMPWS_WSDL_LOCATION = url;
	}

	public EmpWS(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public EmpWS() {
		super(EMPWS_WSDL_LOCATION, new QName("http://test.com/", "EmpWS"));
	}

	/**
	 * 
	 * @return returns WSImpl
	 */
	@WebEndpoint(name = "EmpServices")
	public WSImpl getEmpServices() {
		return super.getPort(new QName("http://test.com/", "EmpServices"),
				WSImpl.class);
	}

}
