
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-23T01:58:46.092+05:30
 * Generated source version: 2.7.3
 * 
 */
public class WSImplClient {

    public static void main(String[] args) throws Exception {
        QName serviceName = new QName("http://test1.com/", "BSImplService");
        QName portName = new QName("http://test1.com/", "juik");

        Service service = Service.create(serviceName);
        service.addPort(portName, SOAPBinding.SOAP11HTTP_BINDING,
                        "http://localhost:7777/MyPort"); 
        WSImpl client = service.getPort(portName,  WSImpl.class);
        
        System.out.println(client.sayHi("Balaji"));
        
        System.out.println(client.sayHello("Balaji"));
        
        // Insert code to invoke methods on the client here
    }

}