// **********************************************************************
//
// Generated by the ORBacus IDL-to-C++ Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.1

#ifndef ___Ex_skel_h__
#define ___Ex_skel_h__

#include <Ex.h>

#include <java/lang/Exception_skel.h>

#ifndef OB_INTEGER_VERSION
#   error No ORBacus version defined! Is <OB/CORBA.h> included?
#endif

#ifndef OB_NO_VERSION_CHECK
#   if (OB_INTEGER_VERSION != 4010100L)
#       error ORBacus version mismatch!
#   endif
#endif

//
// IDL:java:1.0
//
namespace POA_java
{

//
// IDL:java/lang:1.0
//
namespace lang
{

} // End of namespace lang

} // End of namespace POA_java

//
// IDL:java:1.0
//
namespace OBDirectStubImpl_java
{

//
// IDL:java/lang:1.0
//
namespace lang
{

} // End of namespace lang

} // End of namespace OBDirectStubImpl_java

#endif
