-------------------------------------------------------------------------------------------
-- EBILL
-------------------------------------------------------------------------------------------
CREATE TABLE EBILL
(
  EBILL_ID					NUMBER			NOT NULL,
  EBILLER_ID			    NUMBER		    NOT NULL,
  ACCOUNT_ID			    NUMBER          NOT NULL,
  DUE_DATE			        TIMESTAMP	    NOT NULL,
  RECEIVED_DATE			    TIMESTAMP	    NOT NULL,
  MINIMUM_AMOUNT_DUE		NUMBER(10,2)	NOT NULL,
  BALANCE			        NUMBER(10,2)	NOT NULL,
  AMOUNT_PAID			    NUMBER(10,2),
  DATE_PAID             	TIMESTAMP,
  ACCOUNT_TRANSACTION_ID	NUMBER
);

-------------
--PRIMARY KEY
-------------

ALTER TABLE EBILL ADD CONSTRAINT EBILL_PK PRIMARY KEY
    (EBILL_ID) ENABLE;


--------------
--FOREIGN KEYS
--------------

ALTER TABLE EBILL ADD CONSTRAINT EBILL_EBILLERID_EBILLER_FK FOREIGN KEY
    (EBILLER_ID)
    REFERENCES EBILLER (EBILLER_ID) ENABLE;

ALTER TABLE EBILL ADD CONSTRAINT EBILL_ACCTID_ACCT_FK FOREIGN KEY
    (ACCOUNT_ID)
    REFERENCES ACCOUNT (ACCOUNT_ID) ENABLE;
    
ALTER TABLE EBILL ADD CONSTRAINT EBILL_ACCTTXID_ACCTTX_FK FOREIGN KEY
    (ACCOUNT_TRANSACTION_ID)
    REFERENCES ACCOUNT_TRANSACTION (ACCOUNT_TRANSACTION_ID) ENABLE;

