
package com.test;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-23T01:58:46.055+05:30
 * Generated source version: 2.7.3
 * 
 */
 
public class WSImplServer1{

    protected WSImplServer1() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new com.test.BSImpl();
        String address = "http://localhost:7777/MyPort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new WSImplServer1();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
 
 