package com.oracle.enterprisetest.jsca.cart;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.4
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IGetQuantity", targetNamespace = "http://ws.svc.getqty.jsca.enterprisetest.oracle.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IGetQuantity {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTotalQuantity", targetNamespace = "http://ws.svc.getqty.jsca.enterprisetest.oracle.com", className = "com.oracle.enterprisetest.jsca.cart.GetTotalQuantity")
    @ResponseWrapper(localName = "getTotalQuantityResponse", targetNamespace = "http://ws.svc.getqty.jsca.enterprisetest.oracle.com", className = "com.oracle.enterprisetest.jsca.cart.GetTotalQuantityResponse")
    public int getTotalQuantity(
        @WebParam(name = "arg0", targetNamespace = "")
        ShoppingCart arg0);

}
