
package com.javacodegeeks.enterprise.ws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceInterface", targetNamespace = "http://ws.enterprise.javacodegeeks.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceInterface {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "printMessage", targetNamespace = "http://ws.enterprise.javacodegeeks.com/", className = "com.javacodegeeks.enterprise.ws.PrintMessage")
    @ResponseWrapper(localName = "printMessageResponse", targetNamespace = "http://ws.enterprise.javacodegeeks.com/", className = "com.javacodegeeks.enterprise.ws.PrintMessageResponse")
    @Action(input = "http://ws.enterprise.javacodegeeks.com/WebServiceInterface/printMessageRequest", output = "http://ws.enterprise.javacodegeeks.com/WebServiceInterface/printMessageResponse")
    public String printMessage();

}
