<!--
 Copyright 2002 Sun Microsystems, Inc. All rights reserved.
 SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
-->

  <br>
  <!-- ok cancel buttons-->
  <table border="0" cellspacing="0" cellpadding="0" width="100%">
    <tr> 
      <td width="50%"> 
        <div align="right"><input type=image  src="UI/images/buttons/OK.gif" width="70" height="21" name="OK">&nbsp 
          &nbsp</div>
      </td>
      <td width="50%"> 
            <div align="left">&nbsp &nbsp<input type=image src="UI/images/buttons/Cancel.gif" width="66" height="21" name="Cancel"></div>
      </td>
    </tr>
   </table>
   <br>
