<!--
 Copyright 2002 Sun Microsystems, Inc. All rights reserved.
 SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
-->

<head>
  <title><bean:message key="tool.title"/></title>
  <html:base/>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
  <!-- check the validity of inputs -->
  <script language="JavaScript"  src="UI/js/validate.js"> </script>
  <link rel="stylesheet" type="text/css" href="css/clustmgr-style.css">
</head>
