<%--
 
  Copyright 2001 Sun Microsystems, Inc. All Rights Reserved.
  
  This software is the proprietary information of Sun Microsystems, Inc.  
  Use is subject to license terms.
  
--%>


<html>
<head>
    <title>Form Authenticate Sample</title>
</head>

<body bgcolor="white">
<h1><b><center>Form Authentication Sample</center></b></h1>

<p>You are Authenticated Successfully!</p>

</body>
</html>
