package com.test;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-23T02:01:38.376+05:30
 * Generated source version: 2.7.3
 * 
 */
@WebServiceClient(name = "BSImplService", 
                  wsdlLocation = "http://localhost:8080/JAXWS/services/BSImplPort?wsdl",
                  targetNamespace = "http://test.com/") 
public class BSImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://test.com/", "BSImplService");
    public final static QName BSImplPort = new QName("http://test.com/", "BSImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/JAXWS/services/BSImplPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BSImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/JAXWS/services/BSImplPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BSImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BSImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns WSImpl
     */
    @WebEndpoint(name = "BSImplPort")
    public WSImpl getBSImplPort() {
        return super.getPort(BSImplPort, WSImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSImpl
     */
    @WebEndpoint(name = "BSImplPort")
    public WSImpl getBSImplPort(WebServiceFeature... features) {
        return super.getPort(BSImplPort, WSImpl.class, features);
    }

}
